include_guard()

set(RESOURCE_FILES_WINDOWS
	Icon/Windows/Icon.rc
)

list(APPEND RESOURCE_FILES ${RESOURCE_FILES_${PLATFORM_UPPER}})

list(TRANSFORM RESOURCE_FILES PREPEND "${_RESOURCES_DIRECTORY}/")

list(APPEND ALL_FILES ${RESOURCE_FILES})

source_group(TREE ${CMAKE_CURRENT_SOURCE_DIR} FILES ${RESOURCE_FILES})
