include_guard()

set(RESOURCE_FILES_WINDOWS
	Windows/Resource.rc
)

list(APPEND RESOURCE_FILES ${RESOURCE_FILES_${PLATFORM_UPPER}})

list(TRANSFORM RESOURCE_FILES PREPEND "${_RESOURCES_DIRECTORY}/")

source_group(TREE ${CMAKE_CURRENT_SOURCE_DIR} FILES ${RESOURCE_FILES})
