include_guard()

hunter_add_package(Expat)
hunter_add_package(JDKSMIDI)
hunter_add_package(Jpeg)
hunter_add_package(lexilla)
hunter_add_package(nanosvg)
hunter_add_package(pcre2)
hunter_add_package(PNG)
hunter_add_package(scintilla)
hunter_add_package(SndFile)
hunter_add_package(WebP)
hunter_add_package(TIFF)
hunter_add_package(wxWidgets)

find_package(Expat CONFIG REQUIRED)
find_package(JDKSMIDI CONFIG REQUIRED)
find_package(Jpeg CONFIG REQUIRED)
find_package(lexilla CONFIG REQUIRED)
find_package(nanosvg CONFIG REQUIRED)
find_package(pcre2 CONFIG REQUIRED)
find_package(PNG CONFIG REQUIRED)
find_package(OpenGL)
find_package(scintilla CONFIG REQUIRED)
find_package(SndFile CONFIG REQUIRED)
find_package(WebP CONFIG REQUIRED)
find_package(TIFF CONFIG REQUIRED)
find_package(wxWidgets CONFIG REQUIRED)
